export const CREATE_ORDER_USE_CASE = Symbol("CREATE_ORDER_USE_CASE");
export const UPDATE_ORDER_USE_CASE = Symbol("UPDATE_ORDER_USE_CASE");
export const COMPLETE_ORDER_USE_CASE = Symbol("COMPLETE_ORDER_USE_CASE");
export const PUBLISH_OUTBOX_EVENTS_USE_CASE = Symbol("PUBLISH_OUTBOX_EVENTS_USE_CASE");
